"""Cosmos config wiring the dbt project into Airflow.

Imported by lakehouse_daily_pipeline.py.
"""

from __future__ import annotations

from pathlib import Path

from cosmos import ExecutionConfig, LoadMode, ProfileConfig, ProjectConfig, RenderConfig


# The repo root is bind-mounted into the Airflow container at /usr/local/airflow/dbt.
DBT_PROJECT_DIR = Path("/usr/local/airflow/dbt")
DBT_PROFILES_DIR = DBT_PROJECT_DIR  # profiles.yml lives at project root

# Parse the dbt project from the pre-generated manifest rather than shelling out to
# `dbt ls` at DAG-parse time. With the default LoadMode.AUTOMATIC, Cosmos runs `dbt ls`
# once per DbtTaskGroup (bronze/silver/gold = 3×), which cold-starts past Airflow's 30s
# dagbag_import_timeout and breaks the import. manifest.json is generated by
# `make all` / `dbt parse` on the host and is visible here via the bind mount; reading
# it is instant and deterministic.
DBT_MANIFEST_PATH = DBT_PROJECT_DIR / "target" / "manifest.json"

PROJECT_CONFIG = ProjectConfig(
    dbt_project_path=DBT_PROJECT_DIR,
    manifest_path=DBT_MANIFEST_PATH,
)

# Use the project's own profiles.yml (bind-mounted, identical to the host) instead of a
# Cosmos-generated profile. Cosmos's DuckDBUserPasswordProfileMapping emitted a profile
# that dbt-duckdb 1.10 rejected ("Inconsistency between 'path' and 'database' ... database
# must be 'memory' to match the path") — it placed the file in `database`, leaving `path`
# at :memory:. Reusing profiles.yml guarantees host parity (path, memory_limit,
# preserve_insertion_order) and resolves DUCKDB_PATH / DUCKDB_MEMORY_LIMIT from the env.
PROFILE_CONFIG = ProfileConfig(
    profile_name="netflix_lakehouse",
    target_name="dev",
    profiles_yml_filepath=DBT_PROJECT_DIR / "profiles.yml",
)

BRONZE_RENDER = RenderConfig(load_method=LoadMode.DBT_MANIFEST, select=["path:models/bronze"])
SILVER_RENDER = RenderConfig(load_method=LoadMode.DBT_MANIFEST, select=["path:models/silver"])
GOLD_RENDER = RenderConfig(
    load_method=LoadMode.DBT_MANIFEST,
    select=["path:models/gold"],
    exclude=["tag:skip_airflow"],
)
SNAPSHOT_RENDER = RenderConfig(load_method=LoadMode.DBT_MANIFEST, select=["path:snapshots"])

EXECUTION_CONFIG = ExecutionConfig(dbt_executable_path="/usr/local/bin/dbt")
